/*
Course: CS1021

Demonstration code for how to control one stage from another in JavaFX.
Feel free to use this code and modify as needed for your lab

Author: Dr. Sohum Sohoni
 */
package sohoni;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        //create an FXMLLoader object
        FXMLLoader mainLoader = new FXMLLoader();
        //the following line was edited from the original generated by creating a JavaFX app
        Parent root = mainLoader.load(getClass().getResource("mainStage.fxml").openStream());

        //Next 3 lines auto generated by creating a JavaFX app
        primaryStage.setTitle("Hello World");
        primaryStage.setScene(new Scene(root, 300, 275));
        primaryStage.show();

        //code to setup a secondary stage
        MainController mainController = mainLoader.getController();
        mainController.setMainGrid((Pane)root);
        FXMLLoader secondaryLoader = new FXMLLoader();
        Stage secondaryStage = new Stage();
        Parent secondaryRoot = secondaryLoader.load(getClass().getResource("secondaryStage.fxml").openStream());
        SecondaryController secondaryController = secondaryLoader.getController();

        secondaryStage.setScene(new Scene(secondaryRoot));
        secondaryStage.hide(); //this stays hidden until we click a button to show it

        //Code to cross-connect the controllers

        mainController.setOtherStage(secondaryStage);
        mainController.setOtherController(secondaryController);

        secondaryController.setMainStage(primaryStage);
        secondaryController.setMainController(mainController);

        //platform exit makes sure that closing the mainstage will also close the second stage
        primaryStage.setOnCloseRequest(e-> Platform.exit());

    }


    public static void main(String[] args) {
        launch(args);
    }
}
